// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA20CIIHz2N3jjvUIBqV-3Y_8oJpYYMLXE',
    appId: '1:604564869146:web:18bbaf9e256d63bed741a3',
    messagingSenderId: '604564869146',
    projectId: 'pdf-audio-reader-443',
    authDomain: 'pdf-audio-reader-443.firebaseapp.com',
    storageBucket: 'pdf-audio-reader-443.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7I895cxU9eB9hy3qqjCNH2NmQqB6_E7M',
    appId: '1:604564869146:android:a2c5240f9e904566d741a3',
    messagingSenderId: '604564869146',
    projectId: 'pdf-audio-reader-443',
    storageBucket: 'pdf-audio-reader-443.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnOhce1BoyfcCKcgSpCbPVeCQzr8JzPUM',
    appId: '1:604564869146:ios:8e89b48ee19bf57fd741a3',
    messagingSenderId: '604564869146',
    projectId: 'pdf-audio-reader-443',
    storageBucket: 'pdf-audio-reader-443.firebasestorage.app',
    iosBundleId: 'com.nguyenloi.pdfAudioReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnOhce1BoyfcCKcgSpCbPVeCQzr8JzPUM',
    appId: '1:604564869146:ios:8e89b48ee19bf57fd741a3',
    messagingSenderId: '604564869146',
    projectId: 'pdf-audio-reader-443',
    storageBucket: 'pdf-audio-reader-443.firebasestorage.app',
    iosBundleId: 'com.nguyenloi.pdfAudioReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA20CIIHz2N3jjvUIBqV-3Y_8oJpYYMLXE',
    appId: '1:604564869146:web:3331954ac9838516d741a3',
    messagingSenderId: '604564869146',
    projectId: 'pdf-audio-reader-443',
    authDomain: 'pdf-audio-reader-443.firebaseapp.com',
    storageBucket: 'pdf-audio-reader-443.firebasestorage.app',
  );
}
